// Schema (save as player.fbs, then run: flatc --cpp player.fbs)
// ──────────────────────────────────────────────────────────
// namespace game;
//
// struct Vec3 { x:float; y:float; z:float; }
//
// table Player {
//   name:string;
//   score:int32;
//   level:ubyte;
//   pos:Vec3;
//   inventory:[ubyte];
// }
//
// root_type Player;
// ──────────────────────────────────────────────────────────
// compile: g++ -std=c++17 02_flatbuffers.cpp -o 02_flatbuffers -lflatbuffers

// ─────────────────────────────────────────────────────────────────────
// Schema-based FlatBuffers.
//
// Builder pattern: all strings and vectors are created first (they
// become offsets into the buffer), then the table is created, and
// Finish() writes the root offset at the end. The result is a single
// contiguous block ready to write()/sendmsg() without copying.
//
// Verifier: checks all offsets and sizes are in-bounds before reading.
// Run it on untrusted input; skip it on trusted same-process buffers.
// ─────────────────────────────────────────────────────────────────────

#include "player_generated.h" // generated by: flatc --cpp player.fbs
#include <flatbuffers/flatbuffers.h>
#include <iostream>
#include <vector>

int main()
{
    // ── Build ─────────────────────────────────────────────────────────
    flatbuffers::FlatBufferBuilder fbb(256);

    // Strings and vectors must be created before the table that uses them
    auto name = fbb.CreateString("Alice");
    auto inv  = fbb.CreateVector<uint8_t>({10, 20, 30, 40}); // health packs etc.

    game::Vec3 pos(1.0f, 2.5f, 0.0f); // struct: written inline, no offset

    auto player = game::CreatePlayer(fbb,
        name,   // name
        9500,   // score
        7,      // level
        &pos,   // pos
        inv     // inventory
    );

    fbb.Finish(player);

    uint8_t* buf  = fbb.GetBufferPointer();
    int      size = fbb.GetSize();
    std::cout << "buffer: " << size << " bytes\n";

    // ── Verify (bounds-check before reading untrusted data) ───────────
    flatbuffers::Verifier v(buf, size);
    if (!game::VerifyPlayerBuffer(v)) {
        std::cerr << "verification failed\n";
        return 1;
    }

    // ── Read — direct offset access, no allocation ────────────────────
    const game::Player* p = game::GetPlayer(buf);

    std::cout << "name:  " << p->name()->c_str()  << "\n"; // Alice
    std::cout << "score: " << p->score()           << "\n"; // 9500
    std::cout << "level: " << +p->level()          << "\n"; // 7
    std::cout << "pos:   " << p->pos()->x() << " "
                           << p->pos()->y() << " "
                           << p->pos()->z() << "\n";

    std::cout << "inv:   ";
    for (auto byte : *p->inventory()) std::cout << +byte << " ";
    std::cout << "\n";

    // The buffer (buf) can be written directly to a socket or file —
    // no separate serialise step, buf IS the wire format.
}
