// Schema (save as packet.capnp, then run: capnp compile -oc++ packet.capnp)
// ──────────────────────────────────────────────────────────────────────
// @0xdbb9ad1f14bf0b36;
//
// struct Packet {
//   id        @0 :UInt32;
//   timestamp @1 :Int64;
//   payload   @2 :Data;
//   kind      @3 :Kind;
//
//   enum Kind {
//     request  @0;
//     response @1;
//     event    @2;
//   }
// }
// ──────────────────────────────────────────────────────────────────────
// compile: g++ -std=c++17 03_capnproto.cpp packet.capnp.c++ \
//          -o 03_capnproto -lcapnp -lkj

// ─────────────────────────────────────────────────────────────────────
// Cap'n Proto: the wire format IS the in-memory format.
//
// Unlike FlatBuffers, there is no "finish" step — the builder writes
// fields directly into the final layout as you set them.
// messageToFlatArray() produces a word-aligned byte array that is safe
// to pass to write() / sendmsg() with no further transformation.
//
// FlatArrayMessageReader wraps a byte pointer — zero allocation, zero
// parse. getRoot<T>() returns a reader that dereferences offsets
// directly into the original buffer.
// ─────────────────────────────────────────────────────────────────────

#include "packet.capnp.h" // generated by: capnp compile -oc++ packet.capnp
#include <capnp/message.h>
#include <capnp/serialize.h>
#include <kj/array.h>
#include <iostream>
#include <cstring>

int main()
{
    // ── Build ─────────────────────────────────────────────────────────
    capnp::MallocMessageBuilder message;
    auto packet = message.initRoot<Packet>();

    packet.setId(101);
    packet.setTimestamp(1_700_000_000LL);
    packet.setKind(Packet::Kind::REQUEST);

    // Data field (byte buffer)
    const char* body = "hello capnproto";
    auto payload = packet.initPayload(std::strlen(body));
    std::memcpy(payload.begin(), body, std::strlen(body));

    // ── Serialise to a flat byte array (zero-copy wire format) ────────
    kj::Array<capnp::word> words = capnp::messageToFlatArray(message);
    kj::ArrayPtr<const kj::byte> bytes = words.asBytes();
    std::cout << "buffer: " << bytes.size() << " bytes\n";

    // ── Read — wrap the byte array, no allocation ─────────────────────
    // In production: wrap a received buffer directly (mmap, recv, etc.)
    capnp::FlatArrayMessageReader reader(words.asPtr());
    auto pkt = reader.getRoot<Packet>();

    std::cout << "id:        " << pkt.getId()        << "\n"; // 101
    std::cout << "timestamp: " << pkt.getTimestamp()  << "\n";
    std::cout << "kind:      " << static_cast<int>(pkt.getKind()) << "\n"; // 0 = request

    auto pl = pkt.getPayload();
    std::cout << "payload:   "
              << std::string(reinterpret_cast<const char*>(pl.begin()), pl.size())
              << "\n";

    // ── In-place mutation ─────────────────────────────────────────────
    // Cap'n Proto supports mutating fields after initial construction.
    // Use a MutableFlatArrayMessageReader or rebuild from the same builder.
    packet.setId(202); // mutate directly in the builder's buffer
    std::cout << "mutated id: " << message.getRoot<Packet>().getId() << "\n"; // 202
}
